server:
  port: 80
  servlet:
    # 设置 session 的超时时间, 时间的单位是秒, 最少要设置成 60 (1 分钟)
    # 默认时长为 30 分钟
    session:
      timeout: 300s
    # 设置 session 的最大有效数量
spring:
  profiles:
    active: summer

  aop:
    proxy-target-class: false

  redis:
    host: ${easy-spring.redis.server-host}
    port: ${easy-spring.redis.port}
    password: ${easy-spring.redis.passowrd}
    database: 0
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0
    timeout: 3000ms
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${easy-spring.mysql.server-host}:${easy-spring.mysql.port}/${easy-spring.mysql.database}?useUnicode=yes&characterEncode=utf-8&useSSL=false
    username: ${easy-spring.mysql.username}
    password: ${easy-spring.mysql.password}
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8


easy-spring:
  security:
    # 浏览器的配置
    browser:
      # 登录页面的配置
      # loginPage: /demo-signIn.html
      # 登录时的返回方式
      signInResponseType: JSON

    code:
      image:
        length: 2
        width: 100
        urls[0]:
          url: /user/1
          method: GET
          validateCodeType: SMS
      repository: session

    # 第三方登录的相关配置
    social:
      # qq 的配置
      qq:
        # 项目 id
        app-id: ${easy-spring.qq.app-id}
        # 项目密码
        app-secret: ${easy-spring.qq.app-secret}
        # 服务提供商的识别码
        provider-id: callback.do
      # 微信的配置
      we-chat:
        # 项目 id
        app-id: ${easy-spring.we-chat.app-id}
        # 项目密码
        app-secret: ${easy-spring.we-chat.app-secret}
        # 服务提供商的识别码
        provider-id: weixin
      # social 授权后, 若找不到用户, 跳转的路径
      sign-up-url: /demo-signUp.html
      # 配置第三方登录拦截的请求地址前缀
      filter-processes-url: /qqLogin