server:
  port: 8080
spring:
  profiles:
    active: summer

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${easy-spring.mysql.server-host}:${easy-spring.mysql.port}/${easy-spring.mysql.database}?useUnicode=yes&characterEncode=utf-8&useSSL=false
    username: ${easy-spring.mysql.username}
    password: ${easy-spring.mysql.password}
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8


easy-spring:
  security:
    # 浏览器的配置
    browser:
      # 登录页面的配置
      # loginPage: /demo-signIn.html
      # 登录时的返回方式
      signInResponseType: JSON

    code:
      image:
        length: 2
        width: 100
        urls: /user/*



