security:
  oauth2:
    client:
      # 认证者 id
      client-id: spring2
      # 认证者密码
      client-secret: spring-security2
      # 认证地址
      user-authorization-uri: http://127.0.0.1:8080/server/oauth/authorize
      # 获取 accessToken 的地址
      access-token-uri: http://127.0.0.1:8080/server/oauth/token
    resource:
      jwt:
        # 获取 jwt key 的地址
        key-uri: http://127.0.0.1:8080/server/oauth/token_key

server:
  # 端口号
  port: 8082
  servlet:
    # 项目路径
    context-path: /client2
